services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: bglocation
      POSTGRES_PASSWORD: bglocation_dev
      POSTGRES_DB: bglocation
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
